server:
  port: 9000
  netty:
    connection-timeout: 20s
    idle-timeout: 15s
  shutdown: graceful

spring:
  application:
    name: movie-hub-gateway
  lifecycle:
    timeout-per-shutdown-phase: 15s
  config:
    import: "" # When using Config Service, add "optional:configserver:"
  cloud:
    config:
      enabled: false # When using Config Service, set to true
      uri: http://localhost:8888
      request-connect-timeout: 5000 # 5s
      request-read-timeout: 5000 # 5s
      fail-fast: false # In production, set to true
      retry:
        max-attempts: 6
        initial-interval: 1000 # 1s
        max-interval: 2000 # 2s
        multiplier: 1.1
    gateway:
      httpclient:
        connect-timeout: 2000 # 2s
        response-timeout: 20s
        pool:
          type: elastic
          max-idle-time: 15s
          max-life-time: 60s
      default-filters:
        - SaveSession
        - TokenRelay
        - name: RequestRateLimiter
          args:
            redis-rate-limiter:
              replenishRate: 10
              burstCapacity: 20
              requestedTokens: 1
        - name: Retry
          args:
            retries: 3
            methods: GET
            series: SERVER_ERROR
            exceptions: java.io.IOException, java.util.concurrent.TimeoutException
            backoff:
              firstBackoff: 50ms
              maxBackOff: 500ms
              factor: 2
              basedOnPreviousValue: false
      routes:
        - id: spa-route
          uri: ${SPA_URL:http://localhost:9004}
          predicates:
            - Path=/,/*.css,/*.js,/favicon.ico
        - id: movie-route
          uri: ${MOVIES_API_URL:http://localhost:9001}/movies
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/catalog-fallback
        - id: movie-swagger-ui
          uri: ${MOVIES_API_URL:http://localhost:9001}/movies
          predicates:
            - Path=/swagger-ui/**
        - id: movie-swagger-ui-webjars
          uri: ${MOVIES_API_URL:http://localhost:9001}/movies
          predicates:
            - Path=/webjars/**
        - id: movie-openapi
          uri: ${MOVIES_API_URL:http://localhost:9001}/movies
          predicates:
            - Path=/openapi/**
        - id: movie-api-docs
          uri: ${MOVIES_API_URL:http://localhost:9001}/movies
          predicates:
            - Path=/v3/api-docs/**

  redis:
    connect-timeout: 20s
    host: localhost
    port: 6379
    timeout: 20s
  session:
    store-type: redis
    timeout: 10m
    redis:
      namespace: polar:edge
  keycloak:
    server-url: http://localhost:8080
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: edge-service
            client-secret: polar-keycloak-secret
            scope: openid,roles
        provider:
          keycloak:
            issuer-uri: ${spring.keycloak.server-url}/realms/PolarBookshop
      resourceserver:
        jwt:
          issuer-uri: ${spring.keycloak.server-url}/realms/PolarBookshop
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 20
        permittedNumberOfCallsInHalfOpenState: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 15000
  timelimiter:
    configs:
      default:
        timeoutDuration: 5s

logging:
  group:
    circuitbreaker: io.github.resilience4j, org.springframework.cloud.circuitbreaker
  level:
    circuitbreaker: info
  pattern:
    level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"

info:
  system: MOVIE HUB GATEWAY

management:
  endpoints:
    web:
      exposure:
        include: configprops, env, gateway, health, heapdump, info, loggers, mappings, prometheus
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,redis
  info:
    env:
      enabled: true
    java:
      enabled: true
    os:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
